export enum AppRoute {
    AUTH = 'Auth',
    SIGN_IN = 'Sign In',
    SIGN_UP = 'Sign Up',
    RESET_PASSWORD = 'Reset Passrord',
    HOME = 'Home',
    MAIN = 'Main',
    ABOUT = 'About',
    CHECK_LOGIN = 'Check Login',
    LOGOUT = 'Logout',
    PROFILE = 'Profile',
    SEARCH = 'Search',
    SEARCH_MAIN = 'Search_Main',
    CHECK = 'Check',
    CHECK_MAIN = 'Check_Main',
}