export enum AppRoute {
  AUTH = 'Auth',
  SIGN_IN = 'Sign In',
  SIGN_UP = 'Sign Up',
  RESET_PASSWORD = 'Reset Passrord',
  HOME = 'Home',
  MAIN = 'Main',
  ABOUT = 'About',
  CHECK_LOGIN = 'Check Login',
  LOGOUT = 'Logout',
  PROFILE = 'Profile',
  PROFILE_MAIN = 'Profile_Main',
  SEARCH = 'Search',
  SEARCH_MAIN = 'Search_Main',
  SEARCH_DETAIL = 'Search_Detail',
  CHECK = 'Check',
  CHECK_MAIN = 'Check_Main',
  HISTORY = 'Histroy',
  HISTORY_MAIN = 'History_Main',
  APPLY = 'Apply',
  APPLY_MAIN = 'Apply_Main',
  TAB_BAR = 'Tab_bar',
  SIGNUP_DRIVER = 'Signup_Driver',
  SIGNUP_OWNER = 'Signup_Owner',
  SIGNUP_OWNER_MAIN = 'Signup_Owner_Main',
  SIGNUP_DRIVER_MAIN = 'Signup_Driver_Main',
}
